#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/

/register:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          mobilePhone: string
          email: string
          password: string
    responses:
      200:
        description: 注册成功
      404:
        description: 邮箱或者手机号已存在
      500:
        description: 服务器错误

/register/validate-mobile-phone:
  get:
    queryParameters:
      field: string
      value: string
    responses:
      200:
        description: 手机号未注册，通过验证
      404:
        description: 手机号已经存在

/regester/validate-email:
  get:
    queryParameters:
      field: string
      value: string
    responses:
      200:
        description: 邮箱未注册，通过验证
      404:
        description: 邮箱已经存在

/login:
  get:
    

/logicPuzzle/save:
  post:
    body:
      application/json:
        properties:
          orderId: number
          userAnswer: number
          userId: number

    responses:
      200:
        body:

/logic-puzzle:
  get:
    description: 获取logic-puzzle题
    queryParameters:
      orderId: number
    responses:
      200:
        body:
          application/json:
            properties:
              item:
                properties:
                      id: number
                      initializedBox: string
                      question: string
                      descriptinon: string
                      chartPath: string
              userAnswer: number
              itemsCount: number
