#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/

/register:
  post:
    responses:
      200:
        body:
          application/json:
            properties:
              tel:string
              email:string
              password:string

/logicPuzzle/save:
  post:
    body:
      application/json:
        properties:
          orderId: number
          userAnswer: number
          userId: number

    responses:
      200:
        body:

/logic-puzzle:
  get:
    description: 获取logic-puzzle题
    queryParameters:
      orderId: number
    responses:
      200:
        body:
          application/json:
            properties:
              item:
                properties:
                      id: number
                      initializedBox: string
                      question: string
                      descriptinon: string
                      chartPath: string
              userAnswer: number
              itemsCount: number
