#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/
/register:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          mobilePhone: string
          email: string
          password: string
    responses:
      201:
        body:
          application/json:
            properties:
              id: number
              user:
                properties:
                  uri: string
              userInfo:
                properties:
                  uri: string
/login:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          email: string
          password: string
    responses:
      200:
        headers:
          token: string
        body:
          application/json:
            properties:
              id: number
              userInfo:
                properties:
                  uri: string

/logout:
  post:
    headers:
      token: string
    body:
      application/json:
        properties:
          userId: number
    responses:
      201:

/users:
  get:
    queryParameters:
      field: string
      value: string
    responses:
      200:
        body:
          application/json:
            properties:
              uri: string
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                email: string
                mobilePhone: string

    /detail:
      get:
        description: 获取用户信息
        body:
          application/json:
            properties:
              userId: integer
              school: string
              name: string
              gender: string
              major: string
              degree: string
      put:
        description: 提交用户的详细信息
        body:
          application/json:
            properties:
              userId: integer
              school: string
              name: string
              gender: string
              major: string
              degree: string
        responses:
          200:
            body:
              application/json:
                properties:
                  userInfo:
                    properties:
                      uri: string

    /password:
      put:
        description: 修改用户密码
        body:
          application/json:
            properties:
              oldPassword: string
              password: string
        responses:
          200:
            body:
              application/json:
                properties:
                  uri: string

/scoresheets:
  get:
    description: 得到所有的成绩单
    responses:
        200:
          body:
            application/json:
              properties:
                uris: string[]

  post:
    description: 考试完毕，提交成绩单
    body:
      application/json:
        example: |
          {
            "examerId": 1,
            "paperId": 2,
            "blankQuizSubmits": [
              {
                "blankQuizId": 1,
                "itemPosts": [
                  {
                    "answer": "10",
                    "quizItemId": 3
                  }
                ]
              }
            ]
          }
        properties:
          examerId: integer
          paperId: integer
          blankQuizSubmits:
            properties:
              []:
                properties:
                  blankQuizId: integer
                  itemPosts:
                    properties:
                      []:
                        properties:
                          answer: string
                          quizItemId: integer
          [homeworkSubmits]:
            properties:
              []:
                properties:
                  homeworkQuizId: integer
                  homeworkSubmitPostHistory:
                    properties:
                      homeworkURL: string
                      version: string
                      branch: string
                      status: number

    responses:
      201:
        body:
          application/json:
            type: object
            properties:
              uri: string

  /{scoresheetId}:
    get:
      description: 获取成绩单的细节
      responses:
        200:
          body:
            application/json:
              properties:
                examer:
                  properties:
                    uri: string
                paper:
                  properties:
                    uri: string
                blankQuizSubmits[]:
                  properties:
                    blankQuiz:
                      properties:
                       uri: string
                    itemPosts[]:
                      properties:
                        answer: string
                        quizItem:
                          properties:
                            uri: string
                homeworkSubmits[]:
                  properties:
                    homeworkQuiz:
                      properties:
                        uri: string
                    homeworkSubmitPostHistory[]:
                      properties:
                        homeworkURL: string
                        branch: string
                        version: string
                        status: number
                        timestamp: integer

/papers:
  get:
    description: 获得所有的考卷定义
    responses:
      200:
        body:
          application/json:
            properties:
              type[]:
                properties:
                  uri: string

  post:
    description: 提交一份考卷定义，含section定义
    body:
      application/json:
        properties:
          makerId: integer
          sections[]:
            properties:
              description: string
                # description: Markdown String to discribe what happen in the future
              quizzes[]:
                properties:
                  quizId: integer
                  quizType: string
    responses:
      201:
        body:
          application/json:
            properties:
              uri: string
  /{paperId}:
    get:
      description: 获取一份考卷定义的细节，含section的细节
      responses:
        200:
          body:
            # description: quizzes的顺序是有含义的，所以不能乱序
            application/json:
              example: |
                {
                  "id": 1,
                  "sections": [
                    {
                      "id": 1,
                      "description": "逻辑题",
                      "quizzes": [
                        {
                          "id": 1,
                          "definition_uri": "blankQuizzes/1",
                          "items_uri":"blankQuizzes/1/items"
                        }
                      ],
                      "maker_uri": "userInfo/2"
                    }
                  ]
                }
              properties:
                id : integer
                sections:
                  properties:
                    []:
                      properties:
                        id: integer
                        description: string
                          # description: Markdown String to discribe what happen in the future
                        quizzes:
                          properties:
                            []:
                              properties:
                                id: integer
                                definition_uri: string
                                [items_uri]: string
                        maker_uri: string
  /enrollment:
    description: 获取固定ID的考卷定义细节
    get:
      description: 获取一份考卷定义的细节，含section的细节
      responses:
        200:
          body:
            # description: quizzes的顺序是有含义的，所以不能乱序
            application/json:
              example: |
                {
                  "id" :1,
                  "sections": [
                    {
                      "id": 1,
                      "description": "逻辑题",
                      "quizzes": [
                        {
                          "id": 1,
                          "definition_uri": "blankQuizzes/1",
                          "items_uri": "blankQuizzes/1/items"
                        }
                      ],
                      "maker_uri": "userInfo/2"
                    },
                    {
                      "id": 2,
                      "description": "dojo",
                      "quizzes" : [
                        {
                          "id": 1,
                          "definition_uri": "homeworkQuizzes/2"
                        }
                      ],
                      "maker_uri": "userInfo/3"
                    }
                  ]
                }
              properties:
                id: integer
                sections:
                  properties:
                    []:
                      properties:
                        id: integer
                        description: string
                          # description: Markdown String to discribe what happen in the future
                        quizzes:
                          properties:
                            []:
                              properties:
                                id: integer
                                definition_uri: string
                                [items_uri]: string
                        maker_uri: string

/blankQuizzes:
  get:
    # description: 获得所有的填空题定义
    responses:
      200:
        body:
          application/json:
            properties:
              blankQuizzes[]:
                properties:
                  uri: string
  post:
    description: 提交一份填空题定义
    body:
      application/json:
        properties:
          hardCount: integer
          normalCount: integer
          easyCount: integer
          exampleCount: integer
    responses:
      201:
        body:
          application/json:
            properties:
              id: integer
              uri: string
  /{sectionId}:
    get:
      #  description: 获取一份填空题的定义
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                  # description: class name of generator
                hardCount: integer
                normalCount: integer
                easyCount: integer
                exampleCount: integer
  /{blankQuizId}/items:
    get:
      # description: 获取一组题目的内容
      responses:
        200:
          body:
            application/json:
              properties:
                  quizItems:
                    properties:
                        []:
                          properties:
                            id: integer
                            initializedBox: string
                            question: string
                            description: string
                            chartPath: string
                          # 根据前台需要的数据把剩下的补完，不能有正确答案
                  exampleItems:
                    properties:
                        []:
                          properties:
                            id: integer
                            initiallizedBox: string
                            question: string
                            desciption: string
                            chartPath: string
                            answer: string

/quizItems:
  get:
    description: 获取所有的题目项定义
    responses:
      200:
        body:
          application/json:
            properties:
              uri: string
  post:
    description: 提交一份题目项定义
    body:
      application/json:
        properties:
          id: integer
          initializedBox: string
          descriptionZh: string
          chartPath: string
          stepsString: string
          count: integer
          questionZh: string
          stepsLength: integer
          maxUpdateTimes: integer
    responses:
      201:
        body:
          application/json:
            properties:
              uri: string
  /{quizItemId}:
    get:
      description: 获得一份题目项定义的细节
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                initializedBox: string
                question: string
                description: string
                chartPath: string

/homeworkQuizzes:
  get:
    # description: 获得所有的homework题目定义
      responses:
          200:
            body:
              application/json:
                properties:
                  homeworkQuizzes[]:
                    properties:
                      uri: string
  post:
    description: 提交一份homework题目定义
    body:
      application/json:
        properties:
          id: integer
          sectionId: integer
    responses:
      201:
        body:
          application/json:
            properties:
              uri: string
  /{homeworkQuizId}:
    get:
      description: 获得一份homework题目内容
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                description: string
                  # description: Markdown String to discribe homework requirement
                evaluateScript: string
                evaluateRepository: string
                  # description: git url, contain dockerFile in repository
                templateRepository: string
                  # description: git url, contain dockerFile in repository
