#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/

/register:
  post:
    responses:
      200:
        body:
          application/json:
            properties:
              tel:string
              email:string
              password:string

/userPuzzle:
  get:
    request:
      application/json:
        properties:
          userPuzzleIndex: Number

    responses:
      200:
        body:
          application/json:
            properties:
              userAnswer: Number

  post:
    request:
      application/json:
        properties:
          userPuzzle: {
            id: Number
            index: Number
            answer: Number
          }
    responses:
      200:
        body:
          application/json:
            properties:
              status: 200




