TRUNCATE itemPost;
INSERT INTO itemPost VALUES (NULL ,1 ,1 ,"23");
INSERT INTO itemPost VALUES (NULL ,1 ,2 ,"16");
INSERT INTO itemPost VALUES (NULL ,1 ,3 ,"20");
INSERT INTO itemPost VALUES (NULL ,2 ,2 ,"13");
INSERT INTO itemPost VALUES (NULL ,3 ,3 ,"9");
INSERT INTO itemPost VALUES (NULL ,4 ,4 ,"10");