TRUNCATE sectionQuiz;
INSERT INTO sectionQuiz VALUES (NULL ,1,1);
INSERT INTO sectionQuiz VALUES (NULL ,1,2);
INSERT INTO sectionQuiz VALUES (NULL ,2,1);
INSERT INTO sectionQuiz VALUES (NULL ,2,2);
INSERT INTO sectionQuiz VALUES (NULL ,2,3);
INSERT INTO sectionQuiz VALUES (NULL ,2,4);